### ISSUE TITLE
ImportError: cannot import name search

### ISSUE THREAD

**Issue by kn9** [FelixVicis/Google-EmailScraper#2]
Hi Felix, I got the error below when i tried ruining the script again

Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from google import search as GoogleSearch
ImportError: cannot import name search
core7i@4i41:~/Google-EmailScraper#

**Comment by FelixVicis** [comment]
@kn9, you need to install the dependencies. In this particular case, [google](https://github.com/MarioVilas/google).

Simply run `sudo pip install -r requirements.txt` (or your OS equivalent) from the root of the repo.
