### ISSUE TITLE
error when attempting test run

### ISSUE THREAD

**Issue by sheepdogs** [FelixVicis/Google-EmailScraper#6]
/emailcrawl/Google-EmailScraper$ sudo python main.py -query "test" -pages 1 -o emails.csv

Traceback (most recent call last):
  File "main.py", line 76, in <module>
    s.go(args.query, args.pages)
  File "main.py", line 39, in go
    self.scrape(url)
  File "main.py", line 55, in scrape
    pageTitle = re.sub(ReCsvProblemChars, "", soupHtml.title.string)
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by FelixVicis** [comment]
Able to replicate. Working on a fix now.

**Comment by FelixVicis** [comment]
Pull the latest version of master down. The fix is available.

**Comment by sheepdogs** [comment]
Thank you, I will give it a try.
